
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anishmahto
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }
    
    public void close () {
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent (winClosingEvent);
    }
    
    //create a global instance of the EquationSolverAlgorithms class, named equationSolver
    //we create it globally, as multiple methods will need to refer to the same instances of objects within the class
    EquationSolverAlgorithms equationSolver = new EquationSolverAlgorithms();
    //declare booleans to represent whether or not the first and second equations have at least one term of degree one
    //if they dont then they are not linear equations (but rather constant functions), and thus are invalid 
    boolean boolEqnOneHasDegOneTerm = false, boolEqnTwoHasDegOneTerm = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        backgroundPnl = new javax.swing.JPanel();
        addTermEqnOneBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        introLbl = new javax.swing.JLabel();
        eqnOneHeaderLbl = new javax.swing.JLabel();
        eqnTwoHeaderLbl = new javax.swing.JLabel();
        eqnOneLbl = new javax.swing.JLabel();
        eqnTwoLbl = new javax.swing.JLabel();
        eqnOneNumLbl = new javax.swing.JLabel();
        eqnOneDegOne = new javax.swing.JRadioButton();
        eqnOneDenomLbl = new javax.swing.JLabel();
        eqnOneNumTxtIn = new javax.swing.JTextField();
        eqnOneDenomTxtIn = new javax.swing.JTextField();
        eqnTwoNumLbl = new javax.swing.JLabel();
        eqnTwoNumTxtIn = new javax.swing.JTextField();
        eqnTwoDenomLbl = new javax.swing.JLabel();
        eqnTwoDenomTxtIn = new javax.swing.JTextField();
        eqnTwoDegOne = new javax.swing.JRadioButton();
        mainMenuBtn1 = new javax.swing.JButton();
        addTermEqnTwoBtn = new javax.swing.JButton();
        solveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(862, 804));

        backgroundPnl.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPnl.setAutoscrolls(true);
        backgroundPnl.setPreferredSize(new java.awt.Dimension(859, 794));

        addTermEqnOneBtn.setBackground(new java.awt.Color(44, 62, 80));
        addTermEqnOneBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addTermEqnOneBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTermEqnOneBtn.setText("Add Term to Equation 1");
        addTermEqnOneBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addTermEqnOneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTermEqnOneBtnMouseClicked(evt);
            }
        });
        addTermEqnOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTermEqnOneBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titleLbl.setText("Linear System Solver");

        introLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        introLbl.setText("<HTML>This is the Linear System Solver tool! Using this tool, you can input 2 linear equations, and find the solution to their system. To get started, add terms to both equations, and then click <i>Solve</i>. Keep in mind if you do not enter integers for the numerator or denominator, java will end execution of this program.<HTML>");

        eqnOneHeaderLbl.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        eqnOneHeaderLbl.setText("<HTML>Equation 1</HTML>");

        eqnTwoHeaderLbl.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        eqnTwoHeaderLbl.setText("<HTML>Equation 2</HTML>");

        eqnOneLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnOneLbl.setText("<HTML><HTML>");
        eqnOneLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        eqnTwoLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnTwoLbl.setText("<HTML><HTML>");
        eqnTwoLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        eqnOneNumLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnOneNumLbl.setText("<HTML>Numerator of Term:<HTML>");

        eqnOneDegOne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnOneDegOne.setText("<HTML>Click Here If Term is Degree 1<HTML>");
        eqnOneDegOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqnOneDegOneActionPerformed(evt);
            }
        });

        eqnOneDenomLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnOneDenomLbl.setText("<HTML>Denominator of Term:<HTML>");

        eqnTwoNumLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnTwoNumLbl.setText("<HTML>Numerator of Term:<HTML>");

        eqnTwoDenomLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnTwoDenomLbl.setText("<HTML>Denominator of Term:<HTML>");

        eqnTwoDegOne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        eqnTwoDegOne.setText("<HTML>Click Here If Term is Degree 1<HTML>");
        eqnTwoDegOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqnTwoDegOneActionPerformed(evt);
            }
        });

        mainMenuBtn1.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuBtn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuBtn1.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn1.setText("Back To Menu");
        mainMenuBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mainMenuBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuBtn1MouseClicked(evt);
            }
        });
        mainMenuBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtn1ActionPerformed(evt);
            }
        });

        addTermEqnTwoBtn.setBackground(new java.awt.Color(44, 62, 80));
        addTermEqnTwoBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addTermEqnTwoBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTermEqnTwoBtn.setText("Add Term to Equation 2");
        addTermEqnTwoBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addTermEqnTwoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTermEqnTwoBtnMouseClicked(evt);
            }
        });
        addTermEqnTwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTermEqnTwoBtnActionPerformed(evt);
            }
        });

        solveBtn.setBackground(new java.awt.Color(230, 126, 34));
        solveBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        solveBtn.setForeground(new java.awt.Color(255, 255, 255));
        solveBtn.setText("Solve");
        solveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solveBtnMouseClicked(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(231, 76, 60));
        resetBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundPnlLayout = new javax.swing.GroupLayout(backgroundPnl);
        backgroundPnl.setLayout(backgroundPnlLayout);
        backgroundPnlLayout.setHorizontalGroup(
            backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPnlLayout.createSequentialGroup()
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(introLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eqnOneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnOneHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnOneNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnOneDegOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnOneDenomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnOneNumTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnOneDenomTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addTermEqnOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eqnTwoHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnTwoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnTwoNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnTwoDegOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnTwoDenomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnTwoNumTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eqnTwoDenomTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addTermEqnTwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(mainMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(solveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        backgroundPnlLayout.setVerticalGroup(
            backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(introLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqnOneHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqnTwoHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqnOneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqnTwoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addComponent(eqnOneNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqnOneNumTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqnOneDenomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqnOneDenomTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(eqnOneDegOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addComponent(eqnTwoNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqnTwoNumTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqnTwoDenomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqnTwoDenomTxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(eqnTwoDegOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTermEqnOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTermEqnTwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(solveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(mainMenuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jScrollPane1.setViewportView(backgroundPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset () {
        //this method resets everything to false or empty values
        //resent all JFrame object's texts to empty strings
        this.eqnOneLbl.setText("");
        this.eqnTwoLbl.setText("");
        this.eqnOneNumTxtIn.setText("");
        this.eqnTwoNumTxtIn.setText("");
        this.eqnOneDenomTxtIn.setText("");
        this.eqnTwoDenomTxtIn.setText("");
        
        //reset the radio buttons to unselected
        this.eqnOneDegOne.setSelected(false);
        this.eqnTwoDegOne.setSelected(false);
        
        //reset the booleans that check whether or not each equation has a degree one term, as we are reseting both equations
        boolEqnOneHasDegOneTerm = false;
        boolEqnTwoHasDegOneTerm = false;
    }
    
    private void addTermEqnOneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTermEqnOneBtnMouseClicked
        
        if (this.eqnOneNumTxtIn.getText().length() == 0) {
            //if the use has not inputted anything as the numerator, alert this issue through a dialog
            JOptionPane.showMessageDialog(null, "Please enter an integer for the numerator.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (this.eqnOneDenomTxtIn.getText().length() == 0) {
            //if the use has not inputted anything as the denominator, alert this issue through a dialog
            JOptionPane.showMessageDialog(null, "Please enter a denominator. If you do not want a fraction, you can simply set the denominator as 1.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Long.parseLong(this.eqnOneDenomTxtIn.getText())==0) {
            //If the user inputted 0 as the denominator, send an error to the user in the form of a dialog
            JOptionPane.showMessageDialog(null, "The denominator of a number cannot be 0.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //otherwise, the user input is valid, and we need to add this term to our ArrayList
            //parse the input to longs, and store it in appropriate variales
            long longNum = Long.parseLong(this.eqnOneNumTxtIn.getText()), longDenom = Long.parseLong(this.eqnOneDenomTxtIn.getText());
            //check to see if the user selected the radio button, if it is selected then this term will be degree one
            //store the radio choice in the following boolean variable
            boolean boolDegOne = this.eqnOneDegOne.isSelected();
            if (boolDegOne) {
                //if this term is indeed degree one, then we set the global boolean below as true, so that we know that equation one is a linear equation (and not just constant)
                boolEqnOneHasDegOneTerm = true;
            }
            //using the addTerm method in the equationSolver instance, we will add the term based on the info the user inputted
            //for the first paramter I specified a value of true, meaning that this method will add the term to equation 1
            equationSolver.addTerm(true, longNum, longDenom, boolDegOne);
            //finally, output the equation so far to the eqnOneLbl, using the printGlobalEqn() method which returns a string
            //since I specified a paramter of true, it will print out equation one and not equation two
            this.eqnOneLbl.setText(equationSolver.printGlobalEqn(true));
        }
    }//GEN-LAST:event_addTermEqnOneBtnMouseClicked

    private void addTermEqnOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTermEqnOneBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTermEqnOneBtnActionPerformed

    private void eqnOneDegOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqnOneDegOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eqnOneDegOneActionPerformed

    private void eqnTwoDegOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqnTwoDegOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eqnTwoDegOneActionPerformed

    private void mainMenuBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtn1MouseClicked
        //create instance of the MainMenu JFrame, set it to visible, then close this current JFrame
        MainMenu MM = new MainMenu();
        MM.setVisible(true);
        close();
    }//GEN-LAST:event_mainMenuBtn1MouseClicked

    private void mainMenuBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtn1ActionPerformed

    private void addTermEqnTwoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTermEqnTwoBtnMouseClicked
        // TODO add your handling code here:
        if (this.eqnTwoNumTxtIn.getText().length() == 0) {
            //if the use has not inputted anything as the numerator, alert this issue through a dialog
            JOptionPane.showMessageDialog(null, "Please enter an integer for the numerator.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (this.eqnTwoDenomTxtIn.getText().length() == 0) {
            //if the use has not inputted anything as the denominator, alert this issue through a dialog
            JOptionPane.showMessageDialog(null, "Please enter a denominator. If you do not want a fraction, you can simply set the denominator as 1.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Long.parseLong(this.eqnTwoDenomTxtIn.getText())==0) {
            //If the user inputted 0 as the denominator, send an error to the user in the form of a dialog
            JOptionPane.showMessageDialog(null, "The denominator of a number cannot be 0.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //otherwise, the user input is valid, and we need to add this term to our ArrayList
            //parse the input to longs, and store it in appropriate variales
            long longNum = Long.parseLong(this.eqnTwoNumTxtIn.getText()), longDenom = Long.parseLong(this.eqnTwoDenomTxtIn.getText());
            //check to see if the user selected the radio button, if it is selected then this term will be degree one
            //store the radio choice in the following boolean variable
            boolean boolDegOne = this.eqnTwoDegOne.isSelected();
            if (boolDegOne) {
                //if this term is indeed degree one, then we set the global boolean below as true, so that we know that equation one is a linear equation (and not just constant)
                boolEqnTwoHasDegOneTerm = true;
            }
            //using the addTerm method in the equationSolver instance, we will add the term based on the info the user inputted
            //for the first parameter I specified false - this means the term will be added to equation 2
            equationSolver.addTerm(false, longNum, longDenom, boolDegOne);
            //finally, output the equation so far to the eqnOneLbl, using the printGlobalEqn() method which returns a string
            //since I specified a paramter of true, it will print out equation one and not equation two
            this.eqnTwoLbl.setText(equationSolver.printGlobalEqn(false));
        }
    }//GEN-LAST:event_addTermEqnTwoBtnMouseClicked

    private void addTermEqnTwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTermEqnTwoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTermEqnTwoBtnActionPerformed

    private void solveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveBtnMouseClicked
        // TODO add your handling code here:
        if (boolEqnOneHasDegOneTerm && boolEqnTwoHasDegOneTerm) {
            //if both equations have at least one degree one term, they are valid, and so we will solve the system using the solve() method, and print out the steps in a dialog
            //the solve () method accepts two parameters, arraylists for equation 1 and 2
            //those arraylists are also stored in the equationSolver instance, and are called globalEqnOne/globalEqnTwo respectively
            JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + equationSolver.solve (equationSolver.globalEqnOne, equationSolver.globalEqnTwo)), "Solution With Steps", JOptionPane.INFORMATION_MESSAGE);
            //now that we have solved the inputted equation, reset the entire frame
            reset();
            //furthermore, reset the global equation variables in the equationSolver instance, using the equationSolver's local method reset()
            equationSolver.reset();
        } else {
            //otherwise at least one of the two equations are not linear equations, hence alert user using a dialog
            JOptionPane.showMessageDialog(null, "Please ensure both of the equations has at least one degree one term.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_solveBtnMouseClicked

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        //if the reset button is clicked we need to reset the JFrame using the reset method()
        reset();
        //furthermore we need to reset the arrayLists in the equationSolver instance, by using the class' reset() method
        equationSolver.reset();
    }//GEN-LAST:event_resetBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTermEqnOneBtn;
    private javax.swing.JButton addTermEqnTwoBtn;
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JRadioButton eqnOneDegOne;
    private javax.swing.JLabel eqnOneDenomLbl;
    private javax.swing.JTextField eqnOneDenomTxtIn;
    private javax.swing.JLabel eqnOneHeaderLbl;
    private javax.swing.JLabel eqnOneLbl;
    private javax.swing.JLabel eqnOneNumLbl;
    private javax.swing.JTextField eqnOneNumTxtIn;
    private javax.swing.JRadioButton eqnTwoDegOne;
    private javax.swing.JLabel eqnTwoDenomLbl;
    private javax.swing.JTextField eqnTwoDenomTxtIn;
    private javax.swing.JLabel eqnTwoHeaderLbl;
    private javax.swing.JLabel eqnTwoLbl;
    private javax.swing.JLabel eqnTwoNumLbl;
    private javax.swing.JTextField eqnTwoNumTxtIn;
    private javax.swing.JLabel introLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBtn1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton solveBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
