
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anishmahto
 */
public class LessonPartTwo extends javax.swing.JFrame {

    /**
     * Creates new form LessonPartTwo
     */
    public LessonPartTwo() {
        initComponents();
    }

    //this close() method is completely borrowed from the video provided in the announcments page: https://www.youtube.com/watch?v=JW0DDonGqMo 
    public void close () {
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent (winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        backgroundPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainMenuBtn = new javax.swing.JButton();
        lessonPartThreeBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        generateExamplesBtn = new javax.swing.JButton();
        practiceBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(817, 802));

        backgroundPnl.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPnl.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("How Do We Solve A Linear System?");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("<HTML>As mentioned in the <i>What Are Linear Systems</i> section, we defined the solution of a linear system as the point where all linear equations in the system intersect (a.k.a point of intersection, POI). So, how exactly do we solve for the POI of a system?<HTML>");

        mainMenuBtn.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn.setText("Back To Menu");
        mainMenuBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseClicked(evt);
            }
        });

        lessonPartThreeBtn.setBackground(new java.awt.Color(155, 89, 182));
        lessonPartThreeBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lessonPartThreeBtn.setForeground(new java.awt.Color(255, 255, 255));
        lessonPartThreeBtn.setText("Applications Of Linear Systems");
        lessonPartThreeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lessonPartThreeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lessonPartThreeBtnMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("<HTML>At the 9th grade level, we only need to know how to solve linear systems with only 2 equations. However, at the end of this module, I will briefly show you how to solve systems with more than two equations.<HTML>");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("<HTML>If we graph the equations <strong>y = 1/2x + 7</strong> <i>(red)</i> and <strong>y = 3x - 5</strong> <i>(blue)</i>, we can easily see the point of intersection is <strong>(4.8, 9.4)</strong>, or <strong>(24/5, 47/5)</strong> in fraction form.<HTML>");

        jLabel5.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel5.setText("<HTML>y = 1/2 x + 7<br/>y = 3x-5</HTML>");

        jLabel8.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel8.setText("<HTML>Solve By Subsitution</HTML>");

        jLabel14.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel14.setText("<HTML>Solve By Elimination<HTML>");

        jLabel15.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel15.setText("<HTML>Solve By Graphing<HTML>");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("<HTML>The second, and perhaps most common method, is solving by subsitution. Recall that the solution is a point where the both equations produce the same y-value output for the same x-value input. So, the idea is to simply set the y-values equal to each other, and solve for the x-value.<br/><br/>This works because we are saying both equations produce the same output, and solving for the input where that is the case. Notice we could do the same thing, however set the x-values equal to each other and find the corresponding y-value.<HTML>");

        jLabel17.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel17.setText("<HTML><strong>Choose one of the equations:</strong><br/>y = 3x - 5<br/><strong>Plug in x, solve for y:</strong><br/>y = 3 * (24/5) - 5<br/>y = 47/5</HTML>");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("<HTML>Now that we have the x-value of the POI, we can easily solve for the y-value. Since we know the POI lies on <strong>both</strong> linear equations, we can simply pick one and plug in the x-value, and get the corresponding y-value.<HTML>");

        jLabel19.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel19.setText("<HTML><strong>Setting the y-values equal:</strong><br/>1/2x + 7 = 3x - 5<br/><strong>Solving for x:</strong><br/>-5/2x = -12<br/>x = 24/5</HTML>");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("<HTML><strong>Therefore, the POI = (24/5, 47/5)</strong><HTML>");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("<HTML>Perhaps the most intuitive method is to solve the system by graphing. Recall that graphically, the solution of a system is simply the point where all the equations intersect. In this method, we graph both equations, and visually find the point where they intersect<HTML>");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphicalSolutionExample.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setText("<HTML>Let's first learn how to solve systems of 2 equations. I will demonstrate 3 ways to solve 2-equation systems. To work with something tangible, lets say those equations are:<HTML>");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setText("<HTML>The final method is solving by elimination. The idea is to add the two equations so that one of the two variables get eliminated. Let's first re-write our equations to remove any fractions, by multipliying the equations by their denominators:<HTML>");

        jLabel24.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel24.setText("<HTML>2y = x + 14<br/>y = 3x-5</HTML>");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setText("<HTML>Now, we want to add the equations in such a way that the y-variables cancel out (note that you can do this same procedure for the x-variable as well). In other words, we want it such that when we add the equations, the y-variable sums to 0. One way to do this, is by multiplying the second equation by -2.<HTML>");

        jLabel26.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel26.setText("<HTML>2y = x + 14<br/>-2y = -6 x + 10</HTML>");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setText("<HTML>Let's what happens when we add the two equations together now:<HTML>");

        jLabel28.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel28.setText("2y =    x + 14");

        jLabel29.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel29.setText("-2y = -6x + 10");

        jLabel30.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("<HTML><strong>+</strong><HTML>");

        jLabel31.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel31.setText("---------------------");

        jLabel32.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel32.setText("x = 24/5");

        jLabel33.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel33.setText("0 = -5x + 24");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel34.setText("<HTML>Similar to solving by subsitution, at this point we can simply choose one of the equations, plug in the x value, and find the corresponding y-value of the point of intersection. Alas, we get the <strong>POI = (24/5, 47/5).</strong><HTML>");

        jLabel35.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel35.setText("<HTML>Solve Systems With Greater Than 2 Equations<HTML>");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel36.setText("<HTML>As promised, I will briefly explain how to solve systems of greater than 2 equations! The key insight is to realize that if there exists a solution for all equations in the set, it will be equal to the solution for <i>any subset</i> of linear equations in the system. So the idea is simple; first, choose any two equations in the system and solve for their POI. Then, check if the POI calculated lies on every other line in the system (i.e plug in x-value, see if y-value is equal). If the POI does indeed lie on <i>all</i> the lines in the system it is the solution, otherwise there is no solution for the entire system!<HTML>");

        generateExamplesBtn.setBackground(new java.awt.Color(230, 126, 34));
        generateExamplesBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        generateExamplesBtn.setForeground(new java.awt.Color(255, 255, 255));
        generateExamplesBtn.setText("Generate More Examples");
        generateExamplesBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        generateExamplesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateExamplesBtnMouseClicked(evt);
            }
        });

        practiceBtn.setBackground(new java.awt.Color(46, 204, 113));
        practiceBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        practiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        practiceBtn.setText("Practice");
        practiceBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        practiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                practiceBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundPnlLayout = new javax.swing.GroupLayout(backgroundPnl);
        backgroundPnl.setLayout(backgroundPnlLayout);
        backgroundPnlLayout.setHorizontalGroup(
            backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPnlLayout.createSequentialGroup()
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(backgroundPnlLayout.createSequentialGroup()
                                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(generateExamplesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(practiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lessonPartThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(661, Short.MAX_VALUE))
        );
        backgroundPnlLayout.setVerticalGroup(
            backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateExamplesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(practiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessonPartThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(backgroundPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1910, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseClicked
        //create instance of the MainMenu JFrame, set it to visible, then close this current JFrame
        MainMenu MM = new MainMenu ();
        MM.setVisible (true);
        close();
    }//GEN-LAST:event_mainMenuBtnMouseClicked

    private void lessonPartThreeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lessonPartThreeBtnMouseClicked
        //create instance of the LessonPartThree JFrame, set it to visible, then close this current JFrame
        LessonPartThree LPT = new LessonPartThree ();
        LPT.setVisible (true);
        close ();
    }//GEN-LAST:event_lessonPartThreeBtnMouseClicked

    private void generateExamplesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateExamplesBtnMouseClicked
        //create instance of the EquationSolverAlgorithms class I made, call it equationSolver
        EquationSolverAlgorithms equationSolver = new EquationSolverAlgorithms();
        //use the generateAndSolve() method in the class to generate a sample system of equations and solve it. It returns the answer and solution steps formatted together in a string
        String strOutput = equationSolver.generateAndSolve();
        //print out the solution steps/answer in a dialog box
        JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + strOutput), "Generated Example", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_generateExamplesBtnMouseClicked

    private void practiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_practiceBtnMouseClicked
        //create instance of the Practice JFrame, set it to visible, then close this current JFrame
        Practice P = new Practice ();
        P.setVisible(true);
        close();
    }//GEN-LAST:event_practiceBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonPartTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonPartTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonPartTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonPartTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonPartTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JButton generateExamplesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lessonPartThreeBtn;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton practiceBtn;
    // End of variables declaration//GEN-END:variables
}
