
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anishmahto
 */
public class Practice extends javax.swing.JFrame {

    /**
     * Creates new form Practice
     */
    public Practice() {
        initComponents();
    }
    
    //declare a global array that can store 5 strings. Each string at index i will store the solution to the (i+1)th problem generated
    String [] strSolutions = {"", "", "", "", ""};
    
    //this close() method is completely borrowed from the video provided in the announcments page: https://www.youtube.com/watch?v=JW0DDonGqMo
    public void close () {
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent (winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        backgroundPnl = new javax.swing.JPanel();
        mainMenuBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        qOneLbl = new javax.swing.JLabel();
        qTwoLbl = new javax.swing.JLabel();
        showSol1Btn = new javax.swing.JButton();
        qThreeLbl = new javax.swing.JLabel();
        qFourLbl = new javax.swing.JLabel();
        qFiveLbl = new javax.swing.JLabel();
        showSol2Btn = new javax.swing.JButton();
        showSol3Btn = new javax.swing.JButton();
        showSol4Btn = new javax.swing.JButton();
        showSol5Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(862, 804));

        backgroundPnl.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPnl.setAutoscrolls(true);
        backgroundPnl.setPreferredSize(new java.awt.Dimension(859, 794));

        mainMenuBtn.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn.setText("Back To Menu");
        mainMenuBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseClicked(evt);
            }
        });
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Practice Problems");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("<HTML>To get started, please click <i>Generate</i>, to generate a random set of practice problems. To show solutions, please click the respective <i>Show Solution</i> button.<HTML>");

        generateBtn.setBackground(new java.awt.Color(46, 204, 113));
        generateBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        generateBtn.setForeground(new java.awt.Color(255, 255, 255));
        generateBtn.setText("Generate");
        generateBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        generateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateBtnMouseClicked(evt);
            }
        });
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        qOneLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        qOneLbl.setText("<HTML><HTML>");
        qOneLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        qTwoLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        qTwoLbl.setText("<HTML><HTML>");
        qTwoLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        showSol1Btn.setBackground(new java.awt.Color(44, 62, 80));
        showSol1Btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showSol1Btn.setForeground(new java.awt.Color(255, 255, 255));
        showSol1Btn.setText("Show Solution");
        showSol1Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showSol1Btn.setEnabled(false);
        showSol1Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSol1BtnMouseClicked(evt);
            }
        });
        showSol1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSol1BtnActionPerformed(evt);
            }
        });

        qThreeLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        qThreeLbl.setText("<HTML><HTML>");
        qThreeLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        qFourLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        qFourLbl.setText("<HTML><HTML>");
        qFourLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        qFiveLbl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        qFiveLbl.setText("<HTML><HTML>");
        qFiveLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        showSol2Btn.setBackground(new java.awt.Color(44, 62, 80));
        showSol2Btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showSol2Btn.setForeground(new java.awt.Color(255, 255, 255));
        showSol2Btn.setText("Show Solution");
        showSol2Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showSol2Btn.setEnabled(false);
        showSol2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSol2BtnMouseClicked(evt);
            }
        });
        showSol2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSol2BtnActionPerformed(evt);
            }
        });

        showSol3Btn.setBackground(new java.awt.Color(44, 62, 80));
        showSol3Btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showSol3Btn.setForeground(new java.awt.Color(255, 255, 255));
        showSol3Btn.setText("Show Solution");
        showSol3Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showSol3Btn.setEnabled(false);
        showSol3Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSol3BtnMouseClicked(evt);
            }
        });
        showSol3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSol3BtnActionPerformed(evt);
            }
        });

        showSol4Btn.setBackground(new java.awt.Color(44, 62, 80));
        showSol4Btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showSol4Btn.setForeground(new java.awt.Color(255, 255, 255));
        showSol4Btn.setText("Show Solution");
        showSol4Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showSol4Btn.setEnabled(false);
        showSol4Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSol4BtnMouseClicked(evt);
            }
        });
        showSol4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSol4BtnActionPerformed(evt);
            }
        });

        showSol5Btn.setBackground(new java.awt.Color(44, 62, 80));
        showSol5Btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showSol5Btn.setForeground(new java.awt.Color(255, 255, 255));
        showSol5Btn.setText("Show Solution");
        showSol5Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showSol5Btn.setEnabled(false);
        showSol5Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSol5BtnMouseClicked(evt);
            }
        });
        showSol5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSol5BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPnlLayout = new javax.swing.GroupLayout(backgroundPnl);
        backgroundPnl.setLayout(backgroundPnlLayout);
        backgroundPnlLayout.setHorizontalGroup(
            backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPnlLayout.createSequentialGroup()
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPnlLayout.createSequentialGroup()
                                    .addComponent(qFiveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showSol5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPnlLayout.createSequentialGroup()
                                    .addComponent(qFourLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showSol4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPnlLayout.createSequentialGroup()
                                    .addComponent(qThreeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showSol3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPnlLayout.createSequentialGroup()
                                    .addComponent(qTwoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showSol2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPnlLayout.createSequentialGroup()
                                    .addComponent(qOneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(67, 67, 67)
                                    .addComponent(showSol1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        backgroundPnlLayout.setVerticalGroup(
            backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(qOneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(showSol1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(qTwoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(showSol2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(qThreeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(showSol3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(qFourLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(showSol4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(backgroundPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qFiveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPnlLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(showSol5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jScrollPane1.setViewportView(backgroundPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseClicked
        //create instance of the MainMenu JFrame, set it to visible, then close this current JFrame
        MainMenu MM = new MainMenu ();
        MM.setVisible (true);
        close();
    }//GEN-LAST:event_mainMenuBtnMouseClicked

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    private void generateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBtnMouseClicked
        //Once the generate button is clicked, we can enable all the "show solution" buttons, as now the problems will actually exist
        this.showSol1Btn.setEnabled(true);
        this.showSol2Btn.setEnabled(true);
        this.showSol3Btn.setEnabled(true);
        this.showSol4Btn.setEnabled(true);
        this.showSol5Btn.setEnabled(true);
        //create instance of the EquationSolverAlgorithms class, call it equationSolver
        EquationSolverAlgorithms equationSolver = new EquationSolverAlgorithms();
        //generate a system of linear equations and solve it using the generateAndSolve() method for question 1, then store the answer in the corresponding array index
        strSolutions[0] = equationSolver.generateAndSolve ();
        //use the printGlobalEqn() method from the equationSolver object to print out the equations in the question box. Note that if the parameter is true the first equation is printed, else the second equation of the system is printed
        this.qOneLbl.setText("<HTML>" + equationSolver.printGlobalEqn(true) + "<br/>" + equationSolver.printGlobalEqn(false) + "<HTML>");
        
        //generate a system of linear equations and solve it using the generateAndSolve() method for question 2, then store the answer in the corresponding array index
        strSolutions[1] = equationSolver.generateAndSolve ();
        //use the printGlobalEqn() method from the equationSolver object to print out the equations in the question box. Note that if the parameter is true the first equation is printed, else the second equation of the system is printed
        this.qTwoLbl.setText("<HTML>" + equationSolver.printGlobalEqn(true) + "<br/>" + equationSolver.printGlobalEqn(false) + "<HTML>");
        
        //generate a system of linear equations and solve it using the generateAndSolve() method for question 3, then store the answer in the corresponding array index
        strSolutions[2] = equationSolver.generateAndSolve ();
        //use the printGlobalEqn() method from the equationSolver object to print out the equations in the question box. Note that if the parameter is true the first equation is printed, else the second equation of the system is printed
        this.qThreeLbl.setText("<HTML>" + equationSolver.printGlobalEqn(true) + "<br/>" + equationSolver.printGlobalEqn(false) + "<HTML>");
        
        //generate a system of linear equations and solve it using the generateAndSolve() method for question 4, then store the answer in the corresponding array index
        strSolutions[3] = equationSolver.generateAndSolve ();
        //use the printGlobalEqn() method from the equationSolver object to print out the equations in the question box. Note that if the parameter is true the first equation is printed, else the second equation of the system is printed
        this.qFourLbl.setText("<HTML>" + equationSolver.printGlobalEqn(true) + "<br/>" + equationSolver.printGlobalEqn(false) + "<HTML>");
        
        //generate a system of linear equations and solve it using the generateAndSolve() method for question 5, then store the answer in the corresponding array index
        strSolutions[4] = equationSolver.generateAndSolve ();
        //use the printGlobalEqn() method from the equationSolver object to print out the equations in the question box. Note that if the parameter is true the first equation is printed, else the second equation of the system is printed
        this.qFiveLbl.setText("<HTML>" + equationSolver.printGlobalEqn(true) + "<br/>" + equationSolver.printGlobalEqn(false) + "<HTML>");
    }//GEN-LAST:event_generateBtnMouseClicked

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateBtnActionPerformed

    private void showSol1BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSol1BtnMouseClicked
        //get the solution of the first problem which is stored at strSolutions[0], and display it in a dialog
        JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + strSolutions[0]), "Solution With Steps", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showSol1BtnMouseClicked

    private void showSol1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSol1BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSol1BtnActionPerformed

    private void showSol2BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSol2BtnMouseClicked
        //get the solution of the second problem which is stored at strSolutions[1], and display it in a dialog
        JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + strSolutions[1]), "Solution With Steps", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showSol2BtnMouseClicked

    private void showSol2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSol2BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSol2BtnActionPerformed

    private void showSol3BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSol3BtnMouseClicked
        //get the solution of the third problem which is stored at strSolutions[2], and display it in a dialog
        JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + strSolutions[2]), "Solution With Steps", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showSol3BtnMouseClicked

    private void showSol3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSol3BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSol3BtnActionPerformed

    private void showSol4BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSol4BtnMouseClicked
        //get the solution of the fourth problem which is stored at strSolutions[3], and display it in a dialog
        JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + strSolutions[3]), "Solution With Steps", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showSol4BtnMouseClicked

    private void showSol4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSol4BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSol4BtnActionPerformed

    private void showSol5BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSol5BtnMouseClicked
        //get the solution of the fifth problem which is stored at strSolutions[4], and display it in a dialog
        JOptionPane.showMessageDialog(null, ("The following is an example problem/solution generated randomly: \n" + strSolutions[4]), "Solution With Steps", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showSol5BtnMouseClicked

    private void showSol5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSol5BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSol5BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JLabel qFiveLbl;
    private javax.swing.JLabel qFourLbl;
    private javax.swing.JLabel qOneLbl;
    private javax.swing.JLabel qThreeLbl;
    private javax.swing.JLabel qTwoLbl;
    private javax.swing.JButton showSol1Btn;
    private javax.swing.JButton showSol2Btn;
    private javax.swing.JButton showSol3Btn;
    private javax.swing.JButton showSol4Btn;
    private javax.swing.JButton showSol5Btn;
    // End of variables declaration//GEN-END:variables
}
